### ISSUE TITLE
Wrong link highlighting with markdown in the welcome message

### ISSUE THREAD

**Issue by MarcAnt01** [backmeupplz/shieldy#76]
![image](https://user-images.githubusercontent.com/43090263/78995417-94a32800-7b42-11ea-8931-a7f7e696b883.png)

![image](https://user-images.githubusercontent.com/43090263/78995456-abe21580-7b42-11ea-9b0f-5f564c8ba98e.png)

**Comment by backmeupplz** [comment]
Thanks for noticing, I'll fix it when I have time :)

**Comment by backmeupplz** [comment]
Should be fixed, thank you for the report!

**Comment by MarcAnt01** [comment]
@backmeupplz it isn't fixed, the link simply isn't shown now

**Comment by MarcAnt01** [comment]
Can you reopen the issue?
